### PR TITLE
3 set up deployment flow

### LINKED ISSUE #3: Set up deployment flow
We want to set up a proper deployment flow that makes us able to deploy the squids easily.
It seems like subsquid recently introduced so-called [organizations](https://docs.subsquid.io/deploy-squid/organizations/). 
This is a great feature because then we don't rely on single entities to deploy squids but we can share this responsibility between all developers. 

## Todo
- [x] Investigate how we can deploy squids to our `pendulum` organization. 
- [x] Add information about how to deploy the squid for each network to the README
- [x] Make sure that the deployment of the squid to foucoco and amplitude works properly

### PR DESCRIPTION
**Pull request by adelarja**
This PR only changes the README of the project. The development flow was completed while deploying the Amplitude and Foucoco squids.

The deployed squids can be found at the following links:

- [Amplitud](https://app.subsquid.io/squids/amplitude-squid/v1)
- [Foucoco](https://app.subsquid.io/squids/foucoco-squid/v1)

### CODE REVIEW

**Comment by ebma** [comment]
@adelarja IIRC you mentioned that to fix the squid deployments you had to regenerate the db migrations. Wouldn't it make sense to also include those new migrations in this PR? Because the last item in the issue ticket description is:
>  Make sure that the deployment of the squid to foucoco and amplitude works properly

**Comment by ebma** [comment]
@adelarja I added some changes to the README. The changes you added are nice, I just tried to add some improvements to the structure.

**Comment by adelarja** [comment]
> 
@ebma thanks for the comment, you're right. I just added the new file. The migration file is pretty much the same.

**Review by ebma — APPROVED** [review]
The changes to the migration file are enough? That's funny haha. Good job overall 👍

**Pull request merged**
